name: Building YoutubeMatchmaker

on: push

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest  # Runner definition
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone YoutubeMatchmaker repository
        run: |
          git clone https://github.com/udaybuilds/YoutubeMatchmaker.git

      - name: Authenticating Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Building Docker Image
        run: |
          docker build -t youtubematch .

      - name: Tagging Docker Image
        run: |
          docker tag youtubematch udaysivastava/youtubematch:latest

      - name: Pushing Docker Image
        run: |
          docker push udaysivastava/youtubematch:latest