name: Building YoutubeMatchmaker

on: push

jobs:
  my-job:
    name: Checkout Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone YoutubeMatchmaker repository
        run: |
          git clone https://github.com/udaybuilds/YoutubeMatchmaker.git
      - name: Building Docker Image
        run: |
          docker build -t YoutubeMatch .
