name: Building YoutubeMatchmaker

on: push

jobs:
  my-job:
    name: Checkout Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone YoutubeMatchmaker repository
        run: |
          git clone https://github.com/udaybuilds/YoutubeMatchmaker.git

  my-job:
    name: Creating Docker Image
    steps:
      -name: Authenticating GitHub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Building Docker Image
        run: |
          docker build -t youtubematch .
      - name: Tagging Docker Image
        run: |
          docker tag youtubematch udaysivastava/youtubematch:latest
      - name: Pushing Docker Image
        run: |
          docker push udaysivastava/youtubematch:latest
